#!/bin/bash
# Regenerate Sources/SDRGB/SpecText.swift from LEDS_FORMAT.md, so the in-app spec
# viewer and the repo's copy of the DSL reference can never drift apart.
#
#   scripts/embed_spec.sh            # write SpecText.swift
#   scripts/embed_spec.sh --check    # fail if it is out of date (used by CI)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/LEDS_FORMAT.md"
DEST="$ROOT/Sources/SDRGB/SpecText.swift"

# The spec contains backslash escapes inside shell examples (line 16 has a literal
# `\n` in an echo). A plain """ literal would turn those into real newlines and
# silently mangle the in-app text, so we always emit a RAW literal. That is only
# safe while the source never contains the raw literal's terminator.
if grep -q '"""#' "$SRC"; then
    echo "ERROR: $SRC contains '\"\"\"#', which would terminate the raw literal early." >&2
    exit 1
fi

generate() {
    cat <<'HEADER'
/// The LEDS.LED DSL reference, embedded so the in-app spec viewer works no matter
/// where the app is installed.
///
/// GENERATED by scripts/embed_spec.sh from LEDS_FORMAT.md — do not edit by hand.
/// Run `scripts/embed_spec.sh --check` to verify the two are in sync.
///
/// This is deliberately a RAW string literal: the spec contains backslash escapes
/// inside its shell examples, which a plain literal would interpret.
enum SpecText {
    static let content = #"""
HEADER
    cat "$SRC"
    printf '"""#\n}\n'
}

if [ "${1:-}" = "--check" ]; then
    if diff -q <(generate) "$DEST" >/dev/null 2>&1; then
        echo "SpecText.swift is in sync with LEDS_FORMAT.md"
    else
        echo "ERROR: SpecText.swift is out of date. Run scripts/embed_spec.sh" >&2
        diff <(generate) "$DEST" | head -20 >&2 || true
        exit 1
    fi
    exit 0
fi

generate > "$DEST"
echo "wrote $DEST"
